print("List of phrases to translate")
print("Good morning                     |           Buongiorno")
print("                                 |")
print("It is a pleasure to meet you     |           Piacere di conoscerla")
print("                                 |")
print("Please call me tomorrow          |           Perfavore chiamami domani")
print("                                 |")
print("Have a nice day                  |           Buona giornata")